-- Query untuk ambil data stock berdasarkan warehouse
SELECT [warehouse]
      ,[partno]
      ,[desc]
      ,[partname]
      ,[oldpartno]
      ,[group]
      ,[groupkey]
      ,[product_type]
      ,[model]
      ,[customer]
      ,[onhand]
      ,[allocated]
      ,[onorder]
      ,[economicstock]
      ,[safety_stock]
      ,[min_stock]
      ,[max_stock]
      ,[unit]
      ,[location]
  FROM [soi107].[dbo].[stockbywh];

  -- Query untuk ambil data warehouse order header
  SELECT [order_origin_code]
      ,[order_origin]
      ,[trx_type]
      ,[order_date]
      ,[plan_delivery_date]
      ,[ship_from_type]
      ,[ship_from]
      ,[ship_from_desc]
      ,[ship_to_type]
      ,[ship_to]
      ,[ship_to_desc]
  FROM [soi107].[dbo].[view_warehouse_order];

  -- Query untuk ambil data warehouse order line
  SELECT [order_origin_code]
      ,[order_origin]
      ,[trx_type]
      ,[order_date]
      ,[delivery_date]
      ,[receipt_date]
      ,[order_no]
      ,[line_no]
      ,[ship_from_type]
      ,[ship_from]
      ,[ship_from_desc]
      ,[ship_to_type]
      ,[ship_to]
      ,[ship_to_desc]
      ,[item_code]
      ,[item_desc]
      ,[item_desc2]
      ,[order_qty]
      ,[ship_qty]
      ,[unit]
      ,[line_status_code]
      ,[line_status]
  FROM [soi107].[dbo].[view_warehouse_order_line];

  -- Query untuk tarik data shipment
  SELECT [bp_code]
      ,[bp_name]
      ,[sales_order]
      ,[so_date]
      ,[so_line]
      ,[so_sequence]
      ,[customer_po]
      ,[shipment]
      ,[shipment_line]
      ,[delivery_date]
      ,[receipt]
      ,[receipt_line]
      ,[receipt_date]
      ,[part_no]
      ,[old_partno]
      ,[product_type]
      ,[cust_partno]
      ,[cust_partname]
      ,[item_group]
      ,[delivered_qty]
      ,[unit]
      ,[shipment_reference]
      ,[status]
      ,[shipment_status]
      ,[invoice_no]
      ,[inv_line]
      ,[invoice_date]
      ,[invoice_qty]
      ,[currency]
      ,[price]
      ,[amount]
      ,[price_hc]
      ,[amount_hc]
      ,[inv_stat]
      ,[invoice_status]
      ,[dlv_log_date]
  FROM [soi107].[dbo].[so_invoice_line]

  --query untuk tarik data production order
  SELECT TOP (1000) [prod_index]
      ,[prod_no]
      ,[planning_date]
      ,[item]
      ,[old_partno]
      ,[description]
      ,[mat_desc]
      ,[customer]
      ,[model]
      ,[unique_no]
      ,[sanoh_code]
      ,[snp]
      ,[sts]
      ,[status]
      ,[qty_order]
      ,[qty_delivery]
      ,[qty_os]
      ,[warehouse]
      ,[divisi]
  FROM [soi107].[dbo].[view_prod_header];

  --query untuk tarik data receipt PO
  SELECT [po_no]
      ,[bp_id]
      ,[bp_name]
      ,[currency]
      ,[po_type]
      ,[po_reference]
      ,[po_line]
      ,[po_sequence]
      ,[po_receipt_sequence]
      ,[actual_receipt_date]
      ,[actual_receipt_year]
      ,[actual_receipt_period]
      ,[receipt_no]
      ,[receipt_line]
      ,[gr_no]
      ,[packing_slip]
      ,[item_no]
      ,[ics_code]
      ,[ics_part]
      ,[part_no]
      ,[item_desc]
      ,[item_group]
      ,[item_type]
      ,[item_type_desc]
      ,[request_qty]
      ,[actual_receipt_qty]
      ,[approve_qty]
      ,[unit]
      ,[receipt_amount]
      ,[receipt_unit_price]
      ,[is_final_receipt]
      ,[is_confirmed]
      ,[inv_doc_no]
      ,[inv_doc_date]
      ,[inv_qty]
      ,[inv_amount]
      ,[inv_supplier_no]
      ,[inv_due_date]
      ,[payment_doc]
      ,[payment_doc_date]
  FROM [soi107].[dbo].[data_receipt_purchase]


